Refactor to remove abstraction leak into `cluster.ml`
ocurrent/ocurrent-deployer pull request #233
Opened 2024-09-28 03:43 UTC by shonfeder

The current code uses a type like

```ocaml
type service =
  [ `Ci of string
  ; ...
  ; `Ocamlorg_v3c of string 
  ]
```

To mark a field in the deployed services in `pipeline.ml`. Values of this type
are not used anywhere in the project except for `cluster.ml`. In that location,
they are used to map to different applications of `pull_and_serve`. Once we
remove the unused AWS entry, every application of `pull_and_serve` is uniform
*except* that different modules are packed into arguments. The only difference
between these modules is a string value provided when applying the
`Current_docker.Make` to contruct instances of `Current_docker.S.DOCKER`. And
the string value provided there exposes information that we should only know if
you are within the context of a particular deployer.

This PR tries to simplify the situation via the following change: instead of
pre-applying `Current_docker.Make` to special strings, and then using a map from
the `service` type to select the `Current_docker.S.DOCKER` we need, we move the
special string value to the service configuration in `pipeline.ml`, and use
it directly to construct the needed `Current_docker.S.DOCKER`. This
simplification results in the following benefits:

- We remove the `service` type entirely.
- We remove 14 lines of boilerplate functor applications.
- We co-locate the docker context strings with the deployer configurations in
  `pipeline.ml`, further abstracting the "flavours" from the general deployer
  logic, and providing this useful string at the point where we would actually
  want to read it.
- Since we now have this data alongside the services, we are also able to use it
  when generating the `services.md`, so we gain the ability to use this to link
  to the web UI (for most services, the value use for the docker context
  coincides with the service's URL).

A few other incidental cleanups are made along the way. Review by commit may be
useful, tho the diff is not as big as it looks: more than half the new lines are
just from the updated `services.md`, which has a bit more data now and improved
organization.

2024-09-28 03:48 UTC, shonfeder commented
I would like to sync with @mtelvers to discuss the handling of the value used for the docker context, as I think I am abusing that value in the changes to the `services.md` a bit, so I'll leave this as a draft until I get a chance to do so.

2024-10-03 12:43 UTC, shonfeder commented on src/cluster.ml
> -module Ci3_docker = Current_docker.Default
This is the machine that the service is running on.

2024-10-07 02:30 UTC, shonfeder commented on src/pipeline.ml
> +  module Watch_docker = Current_docker.Make(struct let docker_context = Some "watch.ocaml.org" end)
This is moved in from the Cluster module, where it was defined alongside the other functor applications, even tho it wasn't used in that context.

2024-10-07 02:30 UTC, shonfeder commented on src/pipeline.ml
> -    [tarsnap; peertube]
Some of these changes relating to the `v` should have been in a separate commit, that was an oversight on my part. But they were made to simplify and support changes that were needed to complete the main change here, due to the altered representation of the service type.

2024-10-07 02:30 UTC, shonfeder commented on src/pipeline.ml
> -      Cluster_build.repo ?channel ~web_ui ~org ~name builds
This is inlined, to avoid having so many shadowed `build` functions.

2024-10-07 02:30 UTC, shonfeder commented on src/pipeline.ml
> -    docker ~sched t
All this logic is moved into the previous `docker` function, so we can avoid the convoluting shadowing and reuse the same logic more consistently.

2024-10-07 02:30 UTC, shonfeder commented on src/pipeline.ml
> -      Build_registry.repo ?channel ?additional_build_args ~web_ui ~org ~name builds
Rather than constructing a closure and then mapping it, we just construct the values we need in `docker_registry_pipelines`.

2024-10-11 13:36 UTC, shonfeder commented
I've updated this to resolver merge conflicts, and it should be ready for review again.

2024-10-14 11:10 UTC, mtelvers requested changes
Now that the services have mostly coalesced into the same structure these changes improve the readability of the code.  We should either not output the service URL or we should have a separate field allowing us to correctly set the URL for each service.  The previous version shared the Docker context between services which has been unnecessarily lost here.  I'll push a commit with ideas on these points.

2024-10-14 16:41 UTC, mtelvers approved these changes
I've renamed `docker_module` to `docker_context` as it reads much more naturally.  While it is a Docker Module in OCaml, it is a representation of `docker context`.

`images.ci.ocaml.org` is on `ci3.ocamllabs.io`.  My point in the initial review was that you had inadvertently moved it to v3c when you refactored.  The service is, and was, on ci3.

2024-10-14 18:22 UTC, shonfeder commented
Oh, I misunderstood! Thanks for the fix. I agree the naming of the function makes sense.

2024-10-14 18:24 UTC, shonfeder commented
Thanks again for the review and collaboration here! I'm happy with the result :) :raised_hands:

2024-10-15 08:37 UTC, merged